---
title: "excercise 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## 3
```{r}

knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      error = FALSE,
                      results = 'hide',
                      fig.show = 'hide')

```

## 4
```{r}
library(tidyverse)
```

## 5
```{R}
if (!require("rprojroot")) install.packages("rprojroot")
library("rprojroot")
root <- find_root_file(criterion = is_rstudio_project)
root
```

## 6
```{r}
library(readr)
simple_IO <- read_csv(paste0(root, "/data/simple-IO.csv"))
dim(simple_IO)

ncol(simple_IO)

nrow(simple_IO)

#1

#A

head(simple_IO)
dim(simple_IO)
attributes(simple_IO)
summary(simple_IO)

#B simple_IO heeft 11 varabelen
names(simple_IO)

#C Simple_IO heeft 100 rijen
nrow(simple_IO)

#D asf1_del heeft de hoogste expressie ratio met 1.37680
summary(simple_IO)
```

## 7
```{r}
a <- c("a", "b", "c", NA)
b <- c(1:4)
c <- c(6:8, NA)
d <- c(1.3, 1.6, 6.7)
e <- as.integer(d)
f <- as.integer(a)
g <- as.numeric(a)

(z <- paste(a, b, c))
(zz <- paste0(a, b, c))

#A as.integer veranderd chr en num in integer. Dit zijn ronde getallen(?) wanneer het geen getallen zijn zal er een NA weergegeven worden. as.numeric vormt int. en chr. in numeric of geeft NA wanneer de waarde geen getal is.

#E
e
f
g
```


8
```{r}
#3

#A het antwoord is 265
3 + 12 + 250

#B het antwoord is 915
4902 - 3987

#C het antwoord is 16777216
2 ^ 24

#D het antwoord is 17.14286
240/14

#F het antwoord is 16
(12 + 20)/2


#G het antwoord is 13.46667
(10.8 + 13.7 + 15.9) / 3

```

9 
```{r}
##4

#A
vierA <- c(0.5, 20.4, 30.5, 28.9, 5.4)

#B
vierB <- c(as.integer(50:-10))

##C
vierC <- c(seq(from = -10, to = 50))

##D
vierC <- c(seq(from = -10, to = 50), 5)

##E
frep <- c(1,0)
vierE <- c(rep(frep, 500))

##F
set.seed(123); vierF <- runif(100)

##G gemiddelde is 0.498559
mean(vierF)

##H
replace_v5_for_NA <-function(x){
  x[5] <- NA
  return(x)
}

replace_v5_for_NA(vierF)

##I
mean(vierF, na.rm = FALSE)
```

10
```{r}
##5
##A
x <- c(as.integer(1:12))
vijfA <- matrix(data = x, nrow = 3, ncol = 4, byrow = TRUE)

##B
y <- c(as.integer(1:4))
vijfB <- matrix(data = y, nrow = 3, ncol = 4, byrow = TRUE)
## toeoevgen headers colnames(vijfB, "x", "y", "z")
##C
sum(vijfB)
```

11
```{r}
nr <- c(1.8, 4.5, 10.1, 8.3, 7.5)
prime <- c(1, 3, 5, 7, 11)
name <- c("abc1", "foo2", "bar3", "app5", NA)

valid <- c(TRUE, FALSE, FALSE, TRUE, FALSE)
```

12
```{r}

## 

length(nr)
length(prime)
length(name)

length(valid)


name



mydata <- tibble(nr, prime, name, valid)

##

```

